### ISSUE TITLE
Bootloader for M0 Lora board

### ISSUE THREAD

**Issue by asprakash** [adafruit/Adafruit-Feather-M0-RFM-LoRa-PCB#1]
Hi Adafruit team,
I have cloned this board and trying to up the board. However, I am unable to find the bootloader/firmware for this board. Can you please point where can I get the bootloader from Adafruit for this board or Should I use the bootloader from Atmel for ATSAMD21G18A?. Any kind of input is appreciated. 

TIA,
Prakash.

**Comment by ladyada** [comment]
https://github.com/adafruit/ArduinoCore-samd
