### ISSUE TITLE
USB port is not detected. 

### ISSUE THREAD

**Issue by asprakash** [adafruit/Adafruit-Feather-M0-RFM-LoRa-PCB#2]
Thanks for your support. I tried adafruit bootloader for feather and the official hex file, featherm0bootloader_160305.hex and flashed by the jlink programmer. The LED is blinking like heart pulse. However, the USB port is not detected. On windows I am getting "USB port malfunction issue" and on Linux, I am getting the error, "unable to enumerate USB device on port 1". I can confirmed that getting the same issue on multiple boards. 

I also checked this issue, https://github.com/arduino/ArduinoCore-samd/issues/137 So is there any bug on the Adafruit bootloader?.  Any kind of help is appreciated to solve this issue. 

TIA,
Prakash

**Comment by ladyada** [comment]
nope there's no bugs, we don't support DIY projects!
