### ISSUE TITLE
Wrong IRQ pin number in the Feather M0 RFM69 pinout PDF

### ISSUE THREAD

**Issue by DeepCoreSystem** [adafruit/Adafruit-Feather-M0-RFM-LoRa-PCB#4]
Hi,
in the PDF with the Feather M0 RFM69 pinout, the IRQ pin is wrong.

When looking at the schematic, I see that the IRQ should be on pin 3, a.k.a. PA09

**Comment by PeeJay** [comment]
Just took me hours to figure that out!

**Comment by BlitzCityDIY** [comment]
prettypins has been updated
